name: commingle_money
description: "Open-source utilities from the Commingle app (https://commingle.app) for handling, formatting, and displaying monetary values in Flutter."
version: 1.0.1
homepage: https://commingle.app
repository: https://github.com/chris-rutkowski/commingle_money

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  animated_flip_counter: ^0.3.4
  decimal: ^3.2.4
  equatable: ^2.0.8
  expressions: ^0.2.5+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
